---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Example post"
subtitle: "This is my first example post"
summary: "In this post I want to show how to create a blog post with hugodown"
authors: 
tags: 
categories: [R]
date: 2020-07-22
lastmod: 2020-07-22
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

This is my first example post. Lets see how R code gets rendered.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, eval=FALSE}
library(dplyr)
iris %>% 
  glimpse
```



```{r, eval=TRUE}
library(dplyr)

if(1>0) {
  print("Hello")
}
NULL # a comment

a_number <- 232

Inf


iris[,1:5] %>% 
  glimpse
```




