[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.66.0"
  HUGO_BUILDFUTURE = "true"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
